version: "3.8"
services:
    mongodb:
        image: mongo
        ports:
            - "27017:27017"
        logging:
            driver: "none"
    mongo-seed:
        build: ./db
        links:
            - mongodb
        logging:
            driver: "none"
    redis:
        image: 'docker.io/bitnami/redis:6.0-debian-10'
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        ports:
            - '6379:6379'
        logging:
            driver: "none"
    webserver:
        build: .
        volumes:
            - ./:/app
        ports:
            - "8000:5000"
        links:
            - mongodb
            - redis
        environment:
            FLASK_DEBUG: 1
            FLASK_ENV: development
            FLASK_APP: manage.py
            MONGODB_URI: mongodb://mongodb/nopla
            REDIS_URL: 'redis://redis:6379'
            SECRET: xxxxxxxxxxxxxxxxxx

